name: Jupit
favicon: null
layout_spectrum: 0.05147218471392989
typography_spectrum: 0.237323977984488
title: Jupit Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1d7495'
    - '#7166c3'
    - '#96c6c8'
    - '#5faba7'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
